version: '3'
services:

  load-agent:
    build:
      context: .
      target: dev
    hostname: load-agent
    restart: unless-stopped
    user: root 
    tty: true
    working_dir: /load-agent  # Set the working directory
    command: >
      locust -f ${LOCUST_FILES}
    ports:
      - "${START_PORT}-${END_PORT}:${START_PORT}-${END_PORT}"
      - "8089:8089"
    environment: 
      - NODE_ENV=${NODE_ENV}
      - BROWSER=none  # don't open the web browser
      - MEDIATION_URL=${MEDIATION_URL}
      - LOCUST_MIN_WAIT=${LOCUST_MIN_WAIT} # time between pings
      - LOCUST_MAX_WAIT=${LOCUST_MAX_WAIT} # time between pings
      - ISSUER_URL=${ISSUER_URL}
      - ISSUER_HEADERS=${ISSUER_HEADERS}
      - VERIFIER_URL=${VERIFIER_URL}
      - VERIFIER_HEADERS=${VERIFIER_HEADERS}
      - ISSUER_TYPE=${ISSUER_TYPE}
      - VERIFIER_TYPE=${VERIFIER_TYPE}
      - AGENT_IP=${AGENT_IP}
      - CRED_DEF=${CRED_DEF}
      - CRED_ATTR=${CRED_ATTR}
      - SCHEMA=${SCHEMA}
      - CREDENTIAL_FORMAT=${CREDENTIAL_FORMAT}
      - JSONLD_ISSUANCE_PAYLOAD=${JSONLD_ISSUANCE_PAYLOAD}
      - JSONLD_ISSUANCE_DID=${JSONLD_ISSUANCE_DID}
      - JSONLD_VERIFICATION_PAYLOAD=${JSONLD_VERIFICATION_PAYLOAD}
      - LEDGER=${LEDGER}
      - START_PORT=${START_PORT}
      - END_PORT=${END_PORT}
      - MESSAGE_TO_SEND=${MESSAGE_TO_SEND}
      - VERIFIED_TIMEOUT_SECONDS=${VERIFIED_TIMEOUT_SECONDS}
      - WITH_MEDIATION=${WITH_MEDIATION}
      - OOB_INVITE=${OOB_INVITE}
    volumes:
      - ./load-agent:/load-agent:rw
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
